"""
XDR Simulator — Flask API
==========================
Exposes simulation data for the SOC HUD.

Routes:
  GET /                 → serves the SOC HUD
  GET /api/progress     → real-time pipeline state (progress.json)
  GET /api/report       → final simulation report (xdr_report.json)
  GET /api/incidents    → individual IR-*.json reports
  GET /api/status       → health check

Usage:
  python api.py
  then open http://localhost:5000 in your browser
"""

import json
from pathlib import Path

from flask import Flask, jsonify, send_file
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

DATA_DIR = Path("data")
HUD_PATH = Path("xdr_simulator/dashboard/hud.html")


@app.route("/")
def index():
    """Serve the SOC HUD."""
    return send_file(HUD_PATH)


@app.route("/api/status")
def status():
    """Health check."""
    return jsonify({"status": "ok", "data_dir": str(DATA_DIR.resolve())})


@app.route("/api/progress")
def get_progress():
    """Return current pipeline phase written by _write_progress()."""
    path = DATA_DIR / "progress.json"
    if not path.exists():
        return jsonify({"phase": 0, "status": "idle"})
    with open(path, encoding="utf-8") as f:
        return jsonify(json.load(f))


@app.route("/api/report")
def get_report():
    """Return the final XDR report generated by DashboardReporter."""
    path = DATA_DIR / "xdr_report.json"
    if not path.exists():
        return jsonify({"error": "No report yet. Run: python -m xdr_simulator"}), 404
    with open(path, encoding="utf-8") as f:
        return jsonify(json.load(f))


@app.route("/api/incidents")
def get_incidents():
    """Return all individual incident reports (IR-*.json)."""
    incidents = []
    for ir_file in sorted(DATA_DIR.glob("IR-*.json")):
        with open(ir_file, encoding="utf-8") as f:
            incidents.append(json.load(f))
    return jsonify(incidents)


if __name__ == "__main__":
    print("\n  XDR Simulator — API Server")
    print("  → HUD:  http://localhost:5000")
    print("  → http://localhost:5000/api/status")
    print("  → http://localhost:5000/api/progress")
    print("  → http://localhost:5000/api/report")
    print("  → http://localhost:5000/api/incidents\n")
    app.run(debug=True, port=5000)
