"""
Core data models for the XDR Simulator.
Defines normalized event schema and incident structures.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class SourceType(str, Enum):
    """Supported event source types."""
    SYSLOG = "syslog"
    FILEBEAT = "filebeat"
    JSON_API = "json_api"


class Severity(str, Enum):
    """Incident severity levels aligned with PCI-DSS classification."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"
    INFO = "info"


class IncidentType(str, Enum):
    """Types of incidents detected by the XDR engine."""
    SSH_BRUTE_FORCE = "ssh_brute_force"
    ABNORMAL_ACCESS = "abnormal_access"
    PRIVILEGE_ESCALATION = "privilege_escalation"


class EventCategory(str, Enum):
    """Normalized event categories."""
    AUTHENTICATION = "authentication"
    AUTHORIZATION = "authorization"
    NETWORK = "network"
    SYSTEM = "system"
    APPLICATION = "application"
    FILE_ACCESS = "file_access"
    PRIVILEGE_CHANGE = "privilege_change"


@dataclass
class NormalizedEvent:
    """
    Normalized event after parsing.
    All events from different sources are converted to this schema
    for uniform processing in the correlation engine.
    """
    event_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    source_type: SourceType = SourceType.SYSLOG
    source_ip: str = ""
    destination_ip: str = ""
    hostname: str = ""
    username: str = ""
    category: EventCategory = EventCategory.SYSTEM
    action: str = ""
    outcome: str = ""  # "success" | "failure"
    severity: Severity = Severity.INFO
    raw_message: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        d = asdict(self)
        d["source_type"] = self.source_type.value
        d["category"] = self.category.value
        d["severity"] = self.severity.value
        return d


@dataclass
class Incident:
    """
    Security incident generated by the detection engine.
    Groups correlated events that collectively indicate a threat.
    """
    incident_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    incident_type: IncidentType = IncidentType.SSH_BRUTE_FORCE
    severity: Severity = Severity.HIGH
    source_ip: str = ""
    target: str = ""
    description: str = ""
    correlated_events: list[str] = field(default_factory=list)
    event_count: int = 0
    ttd_seconds: float = 0.0  # Time-to-detect
    mitre_tactic: str = ""
    mitre_technique: str = ""
    recommended_action: str = ""
    status: str = "open"  # open | investigating | resolved
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialize to dictionary."""
        d = asdict(self)
        d["incident_type"] = self.incident_type.value
        d["severity"] = self.severity.value
        return d


@dataclass
class CorrelationRule:
    """Definition of a correlation rule for multi-source event linking."""
    rule_id: str
    name: str
    description: str
    event_types: list[EventCategory]
    threshold: int
    time_window_seconds: int
    group_by: list[str]
    severity: Severity = Severity.HIGH
